; AutoHotKey Script Generated by I Can't Automate
F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1, -1
    SetMouseDelay, -1
    SetDefaultMouseSpeed, 0
    SendMode, Input
    ; ---- Start of Macro ----
    ; Disabled
    Sleep, 302
    MouseMove, 882, 674
    Sleep, 107
    MouseMove, 881, 674
    Sleep, 100
    MouseMove, 889, 677
    Click, 874, 682, Down left
    Sleep, 103
    MouseMove, 874, 683
    Click, 871, 685, Up left
    Sleep, 102
    MouseMove, 869, 685
    Sleep, 100
    MouseMove, 764, 714
    Click, 761, 715, Down left
    Sleep, 100
    MouseMove, 753, 724
    Click, 744, 728, Up left
    Sleep, 101
    MouseMove, 670, 778
    Click, 661, 788, Down left
    Sleep, 100
    MouseMove, 661, 798
    Sleep, 104
    MouseMove, 665, 803
    Click, 674, 812, Up left
    Sleep, 101
    MouseMove, 792, 847
    Click, 810, 849, Down left
    Click, 861, 855, Up left
    Sleep, 99
    MouseMove, 976, 829
    Click, 978, 828, Down left
    Sleep, 100
    MouseMove, 1024, 814
    Click, 1027, 813, Up left
    Click, 1054, 782, Down left
    Sleep, 100
    MouseMove, 1055, 782
    Click, 1054, 782, Up left
    Sleep, 102
    MouseMove, 1047, 774
    Click, 987, 726, Down left
    Sleep, 101
    MouseMove, 987, 726
    Click, 950, 722, Up left
    Sleep, 106
    MouseMove, 950, 722
    Click, 718, 723, Down left
    Sleep, 100
    MouseMove, 718, 724
    Click, 718, 724, Up left
    ; Disabled
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
