; AutoHotKey Script Generated by PyWare Automate
F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1
    SetMouseDelay, -1
    SetTitleMatchMode, 1
    SendMode, Input
    ; PixelSearch and conditions test
    PixelSearch, FoundX, FoundY, 745, 775, 1200, 800, 0x43F5F5, 15, Fast
    if (ErrorLevel == 0) {
        Click, %FoundX%, %FoundY%
        Sleep, 500
    } else {
        Click, 1400, 900
    }
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
; --- PyWare Compatibility Layer ---
StartCaptureThread() {
    return
}

StopCaptureThread() {
    return
}
; ---------------------------------

