; AutoHotKey Script Generated by PyWare Automate
F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1
    SetMouseDelay, -1
    SetTitleMatchMode, 
    SendMode, Input
    ; ---- Start of Macro ----
    Sleep, 31
    Send, {F6 up}
    Sleep, 70
    MouseMove, 858, 908
    Sleep, 101
    MouseMove, 862, 914
    Sleep, 95
    Click, 862, 914, Down left
    Sleep, 93
    Click, 862, 914, Up left
    Sleep, 75
    Click, 862, 914, Down left
    Sleep, 81
    Click, 862, 914, Up left
    Sleep, 82
    Click, 862, 914, Down left
    Sleep, 86
    Click, 862, 914, Up left
    Sleep, 81
    Click, 862, 914, Down left
    Sleep, 84
    Click, 862, 914, Up left
    Sleep, 84
    Click, 862, 914, Down left
    Sleep, 81
    Click, 862, 914, Up left
    Sleep, 74
    Click, 862, 914, Down left
    Sleep, 89
    Click, 862, 914, Up left
    Sleep, 141
    Send, {F8 down}
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
; --- PyWare Compatibility Layer ---
StartCaptureThread() {
    return
}

StopCaptureThread() {
    return
}
; ---------------------------------

