; AutoHotKey Script Generated by PyWare Automate
F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1
    SetMouseDelay, -1
    SetTitleMatchMode, 2
    SendMode, Input
    ; ---- Start of Macro ----
    if (%A_Platform% == 0) {
        MsgBox, "You are on macOS. Using Cmd instead of Ctrl."
        ; Script logic for Mac
    } else if (%A_Platform% == 1) {
        MsgBox, "You are on Linux."
    } else {
        MsgBox, "You are on Windows."
    }
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
; --- PyWare Compatibility Layer ---
StartCaptureThread() {
    return
}

StopCaptureThread() {
    return
}
; ---------------------------------

